/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using IO.Swagger.Attributes;
using IO.Swagger.Security;
using Microsoft.AspNetCore.Authorization;
using IO.Swagger.Models;

namespace IO.Swagger.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class CompletionsApiController : ControllerBase
    { 
        /// <summary>
        /// Creates a completion for the provided prompt and parameters.
        /// </summary>
        /// <param name="body"></param>
        /// <response code="200">OK</response>
        [HttpPost]
        [Route("/v1/completions")]
        [Authorize(AuthenticationSchemes = BearerAuthenticationHandler.SchemeName)]
        [ValidateModelState]
        [SwaggerOperation("CreateCompletion")]
        [SwaggerResponse(statusCode: 200, type: typeof(CreateCompletionResponse), description: "OK")]
        public virtual IActionResult CreateCompletion([FromBody]CreateCompletionRequest body)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(CreateCompletionResponse));
            string exampleJson = null;
            exampleJson = "{\n  \"created\" : 5,\n  \"usage\" : {\n    \"completion_tokens\" : 7,\n    \"prompt_tokens\" : 9,\n    \"total_tokens\" : 3\n  },\n  \"model\" : \"model\",\n  \"id\" : \"id\",\n  \"choices\" : [ {\n    \"finish_reason\" : \"stop\",\n    \"index\" : 0,\n    \"text\" : \"text\",\n    \"logprobs\" : {\n      \"top_logprobs\" : [ {\n        \"key\" : 5.962133916683182\n      }, {\n        \"key\" : 5.962133916683182\n      } ],\n      \"token_logprobs\" : [ 1.4658129805029452, 1.4658129805029452 ],\n      \"tokens\" : [ \"tokens\", \"tokens\" ],\n      \"text_offset\" : [ 6, 6 ]\n    }\n  }, {\n    \"finish_reason\" : \"stop\",\n    \"index\" : 0,\n    \"text\" : \"text\",\n    \"logprobs\" : {\n      \"top_logprobs\" : [ {\n        \"key\" : 5.962133916683182\n      }, {\n        \"key\" : 5.962133916683182\n      } ],\n      \"token_logprobs\" : [ 1.4658129805029452, 1.4658129805029452 ],\n      \"tokens\" : [ \"tokens\", \"tokens\" ],\n      \"text_offset\" : [ 6, 6 ]\n    }\n  } ],\n  \"system_fingerprint\" : \"system_fingerprint\",\n  \"object\" : \"text_completion\"\n}";
            
                        var example = exampleJson != null
                        ? JsonConvert.DeserializeObject<CreateCompletionResponse>(exampleJson)
                        : default(CreateCompletionResponse);            //TODO: Change the data returned
            return new ObjectResult(example);
        }
    }
}
