/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using IO.Swagger.Attributes;
using IO.Swagger.Security;
using Microsoft.AspNetCore.Authorization;
using IO.Swagger.Models;

namespace IO.Swagger.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class EmbeddingsApiController : ControllerBase
    { 
        /// <summary>
        /// Creates an embedding vector representing the input text.
        /// </summary>
        /// <param name="body"></param>
        /// <response code="200">OK</response>
        [HttpPost]
        [Route("/v1/embeddings")]
        [Authorize(AuthenticationSchemes = BearerAuthenticationHandler.SchemeName)]
        [ValidateModelState]
        [SwaggerOperation("CreateEmbedding")]
        [SwaggerResponse(statusCode: 200, type: typeof(CreateEmbeddingResponse), description: "OK")]
        public virtual IActionResult CreateEmbedding([FromBody]CreateEmbeddingRequest body)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(CreateEmbeddingResponse));
            string exampleJson = null;
            exampleJson = "{\n  \"data\" : [ {\n    \"index\" : 0,\n    \"embedding\" : [ 6.027456183070403, 6.027456183070403 ],\n    \"object\" : \"embedding\"\n  }, {\n    \"index\" : 0,\n    \"embedding\" : [ 6.027456183070403, 6.027456183070403 ],\n    \"object\" : \"embedding\"\n  } ],\n  \"usage\" : {\n    \"prompt_tokens\" : 1,\n    \"total_tokens\" : 5\n  },\n  \"model\" : \"model\",\n  \"object\" : \"list\"\n}";
            
                        var example = exampleJson != null
                        ? JsonConvert.DeserializeObject<CreateEmbeddingResponse>(exampleJson)
                        : default(CreateEmbeddingResponse);            //TODO: Change the data returned
            return new ObjectResult(example);
        }
    }
}
