/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{
  
          /// <summary>
          /// The role of the author of a message
          /// </summary>
          /// <value>The role of the author of a message</value>
          [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
          public enum ChatCompletionRole
          {
              /// <summary>
              /// Enum SystemEnum for system
              /// </summary>
              [EnumMember(Value = "system")]
              SystemEnum = 0,
              /// <summary>
              /// Enum UserEnum for user
              /// </summary>
              [EnumMember(Value = "user")]
              UserEnum = 1,
              /// <summary>
              /// Enum AssistantEnum for assistant
              /// </summary>
              [EnumMember(Value = "assistant")]
              AssistantEnum = 2,
              /// <summary>
              /// Enum ToolEnum for tool
              /// </summary>
              [EnumMember(Value = "tool")]
              ToolEnum = 3,
              /// <summary>
              /// Enum FunctionEnum for function
              /// </summary>
              [EnumMember(Value = "function")]
              FunctionEnum = 4          }
}
