/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{
    /// <summary>
    /// Usage statistics for the completion request.
    /// </summary>
    [DataContract]
    public partial class CompletionUsage : IEquatable<CompletionUsage>
    { 
        /// <summary>
        /// Number of tokens in the generated completion.
        /// </summary>
        /// <value>Number of tokens in the generated completion.</value>
        [Required]

        [DataMember(Name="completion_tokens")]
        public int? CompletionTokens { get; set; }

        /// <summary>
        /// Number of tokens in the prompt.
        /// </summary>
        /// <value>Number of tokens in the prompt.</value>
        [Required]

        [DataMember(Name="prompt_tokens")]
        public int? PromptTokens { get; set; }

        /// <summary>
        /// Total number of tokens used in the request (prompt + completion).
        /// </summary>
        /// <value>Total number of tokens used in the request (prompt + completion).</value>
        [Required]

        [DataMember(Name="total_tokens")]
        public int? TotalTokens { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CompletionUsage {\n");
            sb.Append("  CompletionTokens: ").Append(CompletionTokens).Append("\n");
            sb.Append("  PromptTokens: ").Append(PromptTokens).Append("\n");
            sb.Append("  TotalTokens: ").Append(TotalTokens).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((CompletionUsage)obj);
        }

        /// <summary>
        /// Returns true if CompletionUsage instances are equal
        /// </summary>
        /// <param name="other">Instance of CompletionUsage to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CompletionUsage other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    CompletionTokens == other.CompletionTokens ||
                    CompletionTokens != null &&
                    CompletionTokens.Equals(other.CompletionTokens)
                ) && 
                (
                    PromptTokens == other.PromptTokens ||
                    PromptTokens != null &&
                    PromptTokens.Equals(other.PromptTokens)
                ) && 
                (
                    TotalTokens == other.TotalTokens ||
                    TotalTokens != null &&
                    TotalTokens.Equals(other.TotalTokens)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (CompletionTokens != null)
                    hashCode = hashCode * 59 + CompletionTokens.GetHashCode();
                    if (PromptTokens != null)
                    hashCode = hashCode * 59 + PromptTokens.GetHashCode();
                    if (TotalTokens != null)
                    hashCode = hashCode * 59 + TotalTokens.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(CompletionUsage left, CompletionUsage right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(CompletionUsage left, CompletionUsage right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
