/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{
    /// <summary>
    /// Represents a streamed chunk of a chat completion response returned by model, based on the provided input.
    /// </summary>
    [DataContract]
    public partial class CreateChatCompletionStreamResponse : IEquatable<CreateChatCompletionStreamResponse>
    { 
        /// <summary>
        /// A unique identifier for the chat completion. Each chunk has the same ID.
        /// </summary>
        /// <value>A unique identifier for the chat completion. Each chunk has the same ID.</value>
        [Required]

        [DataMember(Name="id")]
        public string Id { get; set; }

        /// <summary>
        /// A list of chat completion choices. Can contain more than one elements if &#x60;n&#x60; is greater than 1. Can also be empty for the last chunk if you set &#x60;stream_options: {\&quot;include_usage\&quot;: true}&#x60;. 
        /// </summary>
        /// <value>A list of chat completion choices. Can contain more than one elements if &#x60;n&#x60; is greater than 1. Can also be empty for the last chunk if you set &#x60;stream_options: {\&quot;include_usage\&quot;: true}&#x60;. </value>
        [Required]

        [DataMember(Name="choices")]
        public List<CreateChatCompletionStreamResponseChoices> Choices { get; set; }

        /// <summary>
        /// The Unix timestamp (in seconds) of when the chat completion was created. Each chunk has the same timestamp.
        /// </summary>
        /// <value>The Unix timestamp (in seconds) of when the chat completion was created. Each chunk has the same timestamp.</value>
        [Required]

        [DataMember(Name="created")]
        public int? Created { get; set; }

        /// <summary>
        /// The model to generate the completion.
        /// </summary>
        /// <value>The model to generate the completion.</value>
        [Required]

        [DataMember(Name="model")]
        public string Model { get; set; }

        /// <summary>
        /// The service tier used for processing the request. This field is only included if the `service_tier` parameter is specified in the request.
        /// </summary>
        /// <value>The service tier used for processing the request. This field is only included if the `service_tier` parameter is specified in the request.</value>
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum ServiceTierEnum
        {
            /// <summary>
            /// Enum ScaleEnum for scale
            /// </summary>
            [EnumMember(Value = "scale")]
            ScaleEnum = 0,
            /// <summary>
            /// Enum DefaultEnum for default
            /// </summary>
            [EnumMember(Value = "default")]
            DefaultEnum = 1        }

        /// <summary>
        /// The service tier used for processing the request. This field is only included if the &#x60;service_tier&#x60; parameter is specified in the request.
        /// </summary>
        /// <value>The service tier used for processing the request. This field is only included if the &#x60;service_tier&#x60; parameter is specified in the request.</value>

        [DataMember(Name="service_tier")]
        public ServiceTierEnum? ServiceTier { get; set; }

        /// <summary>
        /// This fingerprint represents the backend configuration that the model runs with. Can be used in conjunction with the &#x60;seed&#x60; request parameter to understand when backend changes have been made that might impact determinism. 
        /// </summary>
        /// <value>This fingerprint represents the backend configuration that the model runs with. Can be used in conjunction with the &#x60;seed&#x60; request parameter to understand when backend changes have been made that might impact determinism. </value>

        [DataMember(Name="system_fingerprint")]
        public string SystemFingerprint { get; set; }

        /// <summary>
        /// The object type, which is always `chat.completion.chunk`.
        /// </summary>
        /// <value>The object type, which is always `chat.completion.chunk`.</value>
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum ObjectEnum
        {
            /// <summary>
            /// Enum ChatCompletionChunkEnum for chat.completion.chunk
            /// </summary>
            [EnumMember(Value = "chat.completion.chunk")]
            ChatCompletionChunkEnum = 0        }

        /// <summary>
        /// The object type, which is always &#x60;chat.completion.chunk&#x60;.
        /// </summary>
        /// <value>The object type, which is always &#x60;chat.completion.chunk&#x60;.</value>
        [Required]

        [DataMember(Name="object")]
        public ObjectEnum? _Object { get; set; }

        /// <summary>
        /// Gets or Sets Usage
        /// </summary>

        [DataMember(Name="usage")]
        public CreateChatCompletionStreamResponseUsage Usage { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CreateChatCompletionStreamResponse {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Choices: ").Append(Choices).Append("\n");
            sb.Append("  Created: ").Append(Created).Append("\n");
            sb.Append("  Model: ").Append(Model).Append("\n");
            sb.Append("  ServiceTier: ").Append(ServiceTier).Append("\n");
            sb.Append("  SystemFingerprint: ").Append(SystemFingerprint).Append("\n");
            sb.Append("  _Object: ").Append(_Object).Append("\n");
            sb.Append("  Usage: ").Append(Usage).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((CreateChatCompletionStreamResponse)obj);
        }

        /// <summary>
        /// Returns true if CreateChatCompletionStreamResponse instances are equal
        /// </summary>
        /// <param name="other">Instance of CreateChatCompletionStreamResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CreateChatCompletionStreamResponse other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Id == other.Id ||
                    Id != null &&
                    Id.Equals(other.Id)
                ) && 
                (
                    Choices == other.Choices ||
                    Choices != null &&
                    Choices.SequenceEqual(other.Choices)
                ) && 
                (
                    Created == other.Created ||
                    Created != null &&
                    Created.Equals(other.Created)
                ) && 
                (
                    Model == other.Model ||
                    Model != null &&
                    Model.Equals(other.Model)
                ) && 
                (
                    ServiceTier == other.ServiceTier ||
                    ServiceTier != null &&
                    ServiceTier.Equals(other.ServiceTier)
                ) && 
                (
                    SystemFingerprint == other.SystemFingerprint ||
                    SystemFingerprint != null &&
                    SystemFingerprint.Equals(other.SystemFingerprint)
                ) && 
                (
                    _Object == other._Object ||
                    _Object != null &&
                    _Object.Equals(other._Object)
                ) && 
                (
                    Usage == other.Usage ||
                    Usage != null &&
                    Usage.Equals(other.Usage)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Id != null)
                    hashCode = hashCode * 59 + Id.GetHashCode();
                    if (Choices != null)
                    hashCode = hashCode * 59 + Choices.GetHashCode();
                    if (Created != null)
                    hashCode = hashCode * 59 + Created.GetHashCode();
                    if (Model != null)
                    hashCode = hashCode * 59 + Model.GetHashCode();
                    if (ServiceTier != null)
                    hashCode = hashCode * 59 + ServiceTier.GetHashCode();
                    if (SystemFingerprint != null)
                    hashCode = hashCode * 59 + SystemFingerprint.GetHashCode();
                    if (_Object != null)
                    hashCode = hashCode * 59 + _Object.GetHashCode();
                    if (Usage != null)
                    hashCode = hashCode * 59 + Usage.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(CreateChatCompletionStreamResponse left, CreateChatCompletionStreamResponse right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(CreateChatCompletionStreamResponse left, CreateChatCompletionStreamResponse right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
