/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class CreateModerationResponseResults : IEquatable<CreateModerationResponseResults>
    { 
        /// <summary>
        /// Whether any of the below categories are flagged.
        /// </summary>
        /// <value>Whether any of the below categories are flagged.</value>
        [Required]

        [DataMember(Name="flagged")]
        public bool? Flagged { get; set; }

        /// <summary>
        /// Gets or Sets Categories
        /// </summary>
        [Required]

        [DataMember(Name="categories")]
        public CreateModerationResponseCategories Categories { get; set; }

        /// <summary>
        /// Gets or Sets CategoryScores
        /// </summary>
        [Required]

        [DataMember(Name="category_scores")]
        public CreateModerationResponseCategoryScores CategoryScores { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CreateModerationResponseResults {\n");
            sb.Append("  Flagged: ").Append(Flagged).Append("\n");
            sb.Append("  Categories: ").Append(Categories).Append("\n");
            sb.Append("  CategoryScores: ").Append(CategoryScores).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((CreateModerationResponseResults)obj);
        }

        /// <summary>
        /// Returns true if CreateModerationResponseResults instances are equal
        /// </summary>
        /// <param name="other">Instance of CreateModerationResponseResults to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CreateModerationResponseResults other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Flagged == other.Flagged ||
                    Flagged != null &&
                    Flagged.Equals(other.Flagged)
                ) && 
                (
                    Categories == other.Categories ||
                    Categories != null &&
                    Categories.Equals(other.Categories)
                ) && 
                (
                    CategoryScores == other.CategoryScores ||
                    CategoryScores != null &&
                    CategoryScores.Equals(other.CategoryScores)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Flagged != null)
                    hashCode = hashCode * 59 + Flagged.GetHashCode();
                    if (Categories != null)
                    hashCode = hashCode * 59 + Categories.GetHashCode();
                    if (CategoryScores != null)
                    hashCode = hashCode * 59 + CategoryScores.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(CreateModerationResponseResults left, CreateModerationResponseResults right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(CreateModerationResponseResults left, CreateModerationResponseResults right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
