/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class CreateTranslationResponseVerboseJson : IEquatable<CreateTranslationResponseVerboseJson>, InlineResponse2001 
    { 
        /// <summary>
        /// The language of the output translation (always &#x60;english&#x60;).
        /// </summary>
        /// <value>The language of the output translation (always &#x60;english&#x60;).</value>
        [Required]

        [DataMember(Name="language")]
        public string Language { get; set; }

        /// <summary>
        /// The duration of the input audio.
        /// </summary>
        /// <value>The duration of the input audio.</value>
        [Required]

        [DataMember(Name="duration")]
        public string Duration { get; set; }

        /// <summary>
        /// The translated text.
        /// </summary>
        /// <value>The translated text.</value>
        [Required]

        [DataMember(Name="text")]
        public string Text { get; set; }

        /// <summary>
        /// Segments of the translated text and their corresponding details.
        /// </summary>
        /// <value>Segments of the translated text and their corresponding details.</value>

        [DataMember(Name="segments")]
        public List<TranscriptionSegment> Segments { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CreateTranslationResponseVerboseJson {\n");
            sb.Append("  Language: ").Append(Language).Append("\n");
            sb.Append("  Duration: ").Append(Duration).Append("\n");
            sb.Append("  Text: ").Append(Text).Append("\n");
            sb.Append("  Segments: ").Append(Segments).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((CreateTranslationResponseVerboseJson)obj);
        }

        /// <summary>
        /// Returns true if CreateTranslationResponseVerboseJson instances are equal
        /// </summary>
        /// <param name="other">Instance of CreateTranslationResponseVerboseJson to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CreateTranslationResponseVerboseJson other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Language == other.Language ||
                    Language != null &&
                    Language.Equals(other.Language)
                ) && 
                (
                    Duration == other.Duration ||
                    Duration != null &&
                    Duration.Equals(other.Duration)
                ) && 
                (
                    Text == other.Text ||
                    Text != null &&
                    Text.Equals(other.Text)
                ) && 
                (
                    Segments == other.Segments ||
                    Segments != null &&
                    Segments.SequenceEqual(other.Segments)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Language != null)
                    hashCode = hashCode * 59 + Language.GetHashCode();
                    if (Duration != null)
                    hashCode = hashCode * 59 + Duration.GetHashCode();
                    if (Text != null)
                    hashCode = hashCode * 59 + Text.GetHashCode();
                    if (Segments != null)
                    hashCode = hashCode * 59 + Segments.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(CreateTranslationResponseVerboseJson left, CreateTranslationResponseVerboseJson right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(CreateTranslationResponseVerboseJson left, CreateTranslationResponseVerboseJson right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
