/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class CreateAssistantRequestToolResourcesFileSearchVectorStores : IEquatable<CreateAssistantRequestToolResourcesFileSearchVectorStores>
    { 
        /// <summary>
        /// A list of [file](/docs/api-reference/files) IDs to add to the vector store. There can be a maximum of 10000 files in a vector store. 
        /// </summary>
        /// <value>A list of [file](/docs/api-reference/files) IDs to add to the vector store. There can be a maximum of 10000 files in a vector store. </value>

        [DataMember(Name="file_ids")]
        public List<string> FileIds { get; set; }

        /// <summary>
        /// The chunking strategy used to chunk the file(s). If not set, will use the &#x60;auto&#x60; strategy.
        /// </summary>
        /// <value>The chunking strategy used to chunk the file(s). If not set, will use the &#x60;auto&#x60; strategy.</value>

        [DataMember(Name="chunking_strategy")]
        public OneOfCreateAssistantRequestToolResourcesFileSearchVectorStoresChunkingStrategy ChunkingStrategy { get; set; }

        /// <summary>
        /// Set of 16 key-value pairs that can be attached to a vector store. This can be useful for storing additional information about the vector store in a structured format. Keys can be a maximum of 64 characters long and values can be a maxium of 512 characters long. 
        /// </summary>
        /// <value>Set of 16 key-value pairs that can be attached to a vector store. This can be useful for storing additional information about the vector store in a structured format. Keys can be a maximum of 64 characters long and values can be a maxium of 512 characters long. </value>

        [DataMember(Name="metadata")]
        public Object Metadata { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CreateAssistantRequestToolResourcesFileSearchVectorStores {\n");
            sb.Append("  FileIds: ").Append(FileIds).Append("\n");
            sb.Append("  ChunkingStrategy: ").Append(ChunkingStrategy).Append("\n");
            sb.Append("  Metadata: ").Append(Metadata).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((CreateAssistantRequestToolResourcesFileSearchVectorStores)obj);
        }

        /// <summary>
        /// Returns true if CreateAssistantRequestToolResourcesFileSearchVectorStores instances are equal
        /// </summary>
        /// <param name="other">Instance of CreateAssistantRequestToolResourcesFileSearchVectorStores to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CreateAssistantRequestToolResourcesFileSearchVectorStores other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    FileIds == other.FileIds ||
                    FileIds != null &&
                    FileIds.SequenceEqual(other.FileIds)
                ) && 
                (
                    ChunkingStrategy == other.ChunkingStrategy ||
                    ChunkingStrategy != null &&
                    ChunkingStrategy.Equals(other.ChunkingStrategy)
                ) && 
                (
                    Metadata == other.Metadata ||
                    Metadata != null &&
                    Metadata.Equals(other.Metadata)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (FileIds != null)
                    hashCode = hashCode * 59 + FileIds.GetHashCode();
                    if (ChunkingStrategy != null)
                    hashCode = hashCode * 59 + ChunkingStrategy.GetHashCode();
                    if (Metadata != null)
                    hashCode = hashCode * 59 + Metadata.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(CreateAssistantRequestToolResourcesFileSearchVectorStores left, CreateAssistantRequestToolResourcesFileSearchVectorStores right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(CreateAssistantRequestToolResourcesFileSearchVectorStores left, CreateAssistantRequestToolResourcesFileSearchVectorStores right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
