/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{
    /// <summary>
    /// Occurs when a stream ends.
    /// </summary>
    [DataContract]
    public partial class DoneEvent : IEquatable<DoneEvent>, AssistantStreamEvent 
    { 
        /// <summary>
        /// Gets or Sets _Event
        /// </summary>
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum EventEnum
        {
            /// <summary>
            /// Enum DoneEnum for done
            /// </summary>
            [EnumMember(Value = "done")]
            DoneEnum = 0        }

        /// <summary>
        /// Gets or Sets _Event
        /// </summary>
        [Required]

        [DataMember(Name="event")]
        public EventEnum? _Event { get; set; }

        /// <summary>
        /// Gets or Sets Data
        /// </summary>
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum DataEnum
        {
            /// <summary>
            /// Enum DONEEnum for [DONE]
            /// </summary>
            [EnumMember(Value = "[DONE]")]
            DONEEnum = 0        }

        /// <summary>
        /// Gets or Sets Data
        /// </summary>
        [Required]

        [DataMember(Name="data")]
        public DataEnum? Data { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class DoneEvent {\n");
            sb.Append("  _Event: ").Append(_Event).Append("\n");
            sb.Append("  Data: ").Append(Data).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((DoneEvent)obj);
        }

        /// <summary>
        /// Returns true if DoneEvent instances are equal
        /// </summary>
        /// <param name="other">Instance of DoneEvent to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DoneEvent other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    _Event == other._Event ||
                    _Event != null &&
                    _Event.Equals(other._Event)
                ) && 
                (
                    Data == other.Data ||
                    Data != null &&
                    Data.Equals(other.Data)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (_Event != null)
                    hashCode = hashCode * 59 + _Event.GetHashCode();
                    if (Data != null)
                    hashCode = hashCode * 59 + Data.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(DoneEvent left, DoneEvent right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(DoneEvent left, DoneEvent right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
