/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{
    /// <summary>
    /// The per-line training example of a fine-tuning input file for completions models
    /// </summary>
    [DataContract]
    public partial class FinetuneCompletionRequestInput : IEquatable<FinetuneCompletionRequestInput>
    { 
        /// <summary>
        /// The input prompt for this training example.
        /// </summary>
        /// <value>The input prompt for this training example.</value>

        [DataMember(Name="prompt")]
        public string Prompt { get; set; }

        /// <summary>
        /// The desired completion for this training example.
        /// </summary>
        /// <value>The desired completion for this training example.</value>

        [DataMember(Name="completion")]
        public string Completion { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class FinetuneCompletionRequestInput {\n");
            sb.Append("  Prompt: ").Append(Prompt).Append("\n");
            sb.Append("  Completion: ").Append(Completion).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((FinetuneCompletionRequestInput)obj);
        }

        /// <summary>
        /// Returns true if FinetuneCompletionRequestInput instances are equal
        /// </summary>
        /// <param name="other">Instance of FinetuneCompletionRequestInput to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(FinetuneCompletionRequestInput other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Prompt == other.Prompt ||
                    Prompt != null &&
                    Prompt.Equals(other.Prompt)
                ) && 
                (
                    Completion == other.Completion ||
                    Completion != null &&
                    Completion.Equals(other.Completion)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Prompt != null)
                    hashCode = hashCode * 59 + Prompt.GetHashCode();
                    if (Completion != null)
                    hashCode = hashCode * 59 + Completion.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(FinetuneCompletionRequestInput left, FinetuneCompletionRequestInput right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(FinetuneCompletionRequestInput left, FinetuneCompletionRequestInput right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
