/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{
    /// <summary>
    /// Metrics at the step number during the fine-tuning job.
    /// </summary>
    [DataContract]
    public partial class FineTuningJobCheckpointMetrics : IEquatable<FineTuningJobCheckpointMetrics>
    { 
        /// <summary>
        /// Gets or Sets Step
        /// </summary>

        [DataMember(Name="step")]
        public decimal? Step { get; set; }

        /// <summary>
        /// Gets or Sets TrainLoss
        /// </summary>

        [DataMember(Name="train_loss")]
        public decimal? TrainLoss { get; set; }

        /// <summary>
        /// Gets or Sets TrainMeanTokenAccuracy
        /// </summary>

        [DataMember(Name="train_mean_token_accuracy")]
        public decimal? TrainMeanTokenAccuracy { get; set; }

        /// <summary>
        /// Gets or Sets ValidLoss
        /// </summary>

        [DataMember(Name="valid_loss")]
        public decimal? ValidLoss { get; set; }

        /// <summary>
        /// Gets or Sets ValidMeanTokenAccuracy
        /// </summary>

        [DataMember(Name="valid_mean_token_accuracy")]
        public decimal? ValidMeanTokenAccuracy { get; set; }

        /// <summary>
        /// Gets or Sets FullValidLoss
        /// </summary>

        [DataMember(Name="full_valid_loss")]
        public decimal? FullValidLoss { get; set; }

        /// <summary>
        /// Gets or Sets FullValidMeanTokenAccuracy
        /// </summary>

        [DataMember(Name="full_valid_mean_token_accuracy")]
        public decimal? FullValidMeanTokenAccuracy { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class FineTuningJobCheckpointMetrics {\n");
            sb.Append("  Step: ").Append(Step).Append("\n");
            sb.Append("  TrainLoss: ").Append(TrainLoss).Append("\n");
            sb.Append("  TrainMeanTokenAccuracy: ").Append(TrainMeanTokenAccuracy).Append("\n");
            sb.Append("  ValidLoss: ").Append(ValidLoss).Append("\n");
            sb.Append("  ValidMeanTokenAccuracy: ").Append(ValidMeanTokenAccuracy).Append("\n");
            sb.Append("  FullValidLoss: ").Append(FullValidLoss).Append("\n");
            sb.Append("  FullValidMeanTokenAccuracy: ").Append(FullValidMeanTokenAccuracy).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((FineTuningJobCheckpointMetrics)obj);
        }

        /// <summary>
        /// Returns true if FineTuningJobCheckpointMetrics instances are equal
        /// </summary>
        /// <param name="other">Instance of FineTuningJobCheckpointMetrics to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(FineTuningJobCheckpointMetrics other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Step == other.Step ||
                    Step != null &&
                    Step.Equals(other.Step)
                ) && 
                (
                    TrainLoss == other.TrainLoss ||
                    TrainLoss != null &&
                    TrainLoss.Equals(other.TrainLoss)
                ) && 
                (
                    TrainMeanTokenAccuracy == other.TrainMeanTokenAccuracy ||
                    TrainMeanTokenAccuracy != null &&
                    TrainMeanTokenAccuracy.Equals(other.TrainMeanTokenAccuracy)
                ) && 
                (
                    ValidLoss == other.ValidLoss ||
                    ValidLoss != null &&
                    ValidLoss.Equals(other.ValidLoss)
                ) && 
                (
                    ValidMeanTokenAccuracy == other.ValidMeanTokenAccuracy ||
                    ValidMeanTokenAccuracy != null &&
                    ValidMeanTokenAccuracy.Equals(other.ValidMeanTokenAccuracy)
                ) && 
                (
                    FullValidLoss == other.FullValidLoss ||
                    FullValidLoss != null &&
                    FullValidLoss.Equals(other.FullValidLoss)
                ) && 
                (
                    FullValidMeanTokenAccuracy == other.FullValidMeanTokenAccuracy ||
                    FullValidMeanTokenAccuracy != null &&
                    FullValidMeanTokenAccuracy.Equals(other.FullValidMeanTokenAccuracy)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Step != null)
                    hashCode = hashCode * 59 + Step.GetHashCode();
                    if (TrainLoss != null)
                    hashCode = hashCode * 59 + TrainLoss.GetHashCode();
                    if (TrainMeanTokenAccuracy != null)
                    hashCode = hashCode * 59 + TrainMeanTokenAccuracy.GetHashCode();
                    if (ValidLoss != null)
                    hashCode = hashCode * 59 + ValidLoss.GetHashCode();
                    if (ValidMeanTokenAccuracy != null)
                    hashCode = hashCode * 59 + ValidMeanTokenAccuracy.GetHashCode();
                    if (FullValidLoss != null)
                    hashCode = hashCode * 59 + FullValidLoss.GetHashCode();
                    if (FullValidMeanTokenAccuracy != null)
                    hashCode = hashCode * 59 + FullValidMeanTokenAccuracy.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(FineTuningJobCheckpointMetrics left, FineTuningJobCheckpointMetrics right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(FineTuningJobCheckpointMetrics left, FineTuningJobCheckpointMetrics right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
