/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{
    /// <summary>
    /// On an incomplete message, details about why the message is incomplete.
    /// </summary>
    [DataContract]
    public partial class MessageObjectIncompleteDetails : IEquatable<MessageObjectIncompleteDetails>
    { 
        /// <summary>
        /// The reason the message is incomplete.
        /// </summary>
        /// <value>The reason the message is incomplete.</value>
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum ReasonEnum
        {
            /// <summary>
            /// Enum ContentFilterEnum for content_filter
            /// </summary>
            [EnumMember(Value = "content_filter")]
            ContentFilterEnum = 0,
            /// <summary>
            /// Enum MaxTokensEnum for max_tokens
            /// </summary>
            [EnumMember(Value = "max_tokens")]
            MaxTokensEnum = 1,
            /// <summary>
            /// Enum RunCancelledEnum for run_cancelled
            /// </summary>
            [EnumMember(Value = "run_cancelled")]
            RunCancelledEnum = 2,
            /// <summary>
            /// Enum RunExpiredEnum for run_expired
            /// </summary>
            [EnumMember(Value = "run_expired")]
            RunExpiredEnum = 3,
            /// <summary>
            /// Enum RunFailedEnum for run_failed
            /// </summary>
            [EnumMember(Value = "run_failed")]
            RunFailedEnum = 4        }

        /// <summary>
        /// The reason the message is incomplete.
        /// </summary>
        /// <value>The reason the message is incomplete.</value>
        [Required]

        [DataMember(Name="reason")]
        public ReasonEnum? Reason { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class MessageObjectIncompleteDetails {\n");
            sb.Append("  Reason: ").Append(Reason).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((MessageObjectIncompleteDetails)obj);
        }

        /// <summary>
        /// Returns true if MessageObjectIncompleteDetails instances are equal
        /// </summary>
        /// <param name="other">Instance of MessageObjectIncompleteDetails to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(MessageObjectIncompleteDetails other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Reason == other.Reason ||
                    Reason != null &&
                    Reason.Equals(other.Reason)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Reason != null)
                    hashCode = hashCode * 59 + Reason.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(MessageObjectIncompleteDetails left, MessageObjectIncompleteDetails right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(MessageObjectIncompleteDetails left, MessageObjectIncompleteDetails right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
