/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{
    /// <summary>
    /// Details of the message creation by the run step.
    /// </summary>
    [DataContract]
    public partial class RunStepDeltaStepDetailsMessageCreationObject : IEquatable<RunStepDeltaStepDetailsMessageCreationObject>, OneOfRunStepDeltaObjectDeltaStepDetails 
    { 
        /// <summary>
        /// Always `message_creation`.
        /// </summary>
        /// <value>Always `message_creation`.</value>
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum TypeEnum
        {
            /// <summary>
            /// Enum MessageCreationEnum for message_creation
            /// </summary>
            [EnumMember(Value = "message_creation")]
            MessageCreationEnum = 0        }

        /// <summary>
        /// Always &#x60;message_creation&#x60;.
        /// </summary>
        /// <value>Always &#x60;message_creation&#x60;.</value>
        [Required]

        [DataMember(Name="type")]
        public TypeEnum? Type { get; set; }

        /// <summary>
        /// Gets or Sets MessageCreation
        /// </summary>

        [DataMember(Name="message_creation")]
        public RunStepDeltaStepDetailsMessageCreationObjectMessageCreation MessageCreation { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class RunStepDeltaStepDetailsMessageCreationObject {\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  MessageCreation: ").Append(MessageCreation).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((RunStepDeltaStepDetailsMessageCreationObject)obj);
        }

        /// <summary>
        /// Returns true if RunStepDeltaStepDetailsMessageCreationObject instances are equal
        /// </summary>
        /// <param name="other">Instance of RunStepDeltaStepDetailsMessageCreationObject to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(RunStepDeltaStepDetailsMessageCreationObject other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Type == other.Type ||
                    Type != null &&
                    Type.Equals(other.Type)
                ) && 
                (
                    MessageCreation == other.MessageCreation ||
                    MessageCreation != null &&
                    MessageCreation.Equals(other.MessageCreation)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Type != null)
                    hashCode = hashCode * 59 + Type.GetHashCode();
                    if (MessageCreation != null)
                    hashCode = hashCode * 59 + MessageCreation.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(RunStepDeltaStepDetailsMessageCreationObject left, RunStepDeltaStepDetailsMessageCreationObject right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(RunStepDeltaStepDetailsMessageCreationObject left, RunStepDeltaStepDetailsMessageCreationObject right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
