/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class StaticChunkingStrategyRequestParam : IEquatable<StaticChunkingStrategyRequestParam>, ChunkingStrategyRequestParam, OneOfCreateVectorStoreRequestChunkingStrategy 
    { 
        /// <summary>
        /// Always `static`.
        /// </summary>
        /// <value>Always `static`.</value>
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum TypeEnum
        {
            /// <summary>
            /// Enum StaticEnum for static
            /// </summary>
            [EnumMember(Value = "static")]
            StaticEnum = 0        }

        /// <summary>
        /// Always &#x60;static&#x60;.
        /// </summary>
        /// <value>Always &#x60;static&#x60;.</value>
        [Required]

        [DataMember(Name="type")]
        public TypeEnum? Type { get; set; }

        /// <summary>
        /// Gets or Sets _Static
        /// </summary>
        [Required]

        [DataMember(Name="static")]
        public StaticChunkingStrategy _Static { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class StaticChunkingStrategyRequestParam {\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  _Static: ").Append(_Static).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((StaticChunkingStrategyRequestParam)obj);
        }

        /// <summary>
        /// Returns true if StaticChunkingStrategyRequestParam instances are equal
        /// </summary>
        /// <param name="other">Instance of StaticChunkingStrategyRequestParam to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(StaticChunkingStrategyRequestParam other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Type == other.Type ||
                    Type != null &&
                    Type.Equals(other.Type)
                ) && 
                (
                    _Static == other._Static ||
                    _Static != null &&
                    _Static.Equals(other._Static)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Type != null)
                    hashCode = hashCode * 59 + Type.GetHashCode();
                    if (_Static != null)
                    hashCode = hashCode * 59 + _Static.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(StaticChunkingStrategyRequestParam left, StaticChunkingStrategyRequestParam right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(StaticChunkingStrategyRequestParam left, StaticChunkingStrategyRequestParam right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
