/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class SubmitToolOutputsRunRequest : IEquatable<SubmitToolOutputsRunRequest>
    { 
        /// <summary>
        /// A list of tools for which the outputs are being submitted.
        /// </summary>
        /// <value>A list of tools for which the outputs are being submitted.</value>
        [Required]

        [DataMember(Name="tool_outputs")]
        public List<SubmitToolOutputsRunRequestToolOutputs> ToolOutputs { get; set; }

        /// <summary>
        /// If &#x60;true&#x60;, returns a stream of events that happen during the Run as server-sent events, terminating when the Run enters a terminal state with a &#x60;data: [DONE]&#x60; message. 
        /// </summary>
        /// <value>If &#x60;true&#x60;, returns a stream of events that happen during the Run as server-sent events, terminating when the Run enters a terminal state with a &#x60;data: [DONE]&#x60; message. </value>

        [DataMember(Name="stream")]
        public bool? Stream { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SubmitToolOutputsRunRequest {\n");
            sb.Append("  ToolOutputs: ").Append(ToolOutputs).Append("\n");
            sb.Append("  Stream: ").Append(Stream).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((SubmitToolOutputsRunRequest)obj);
        }

        /// <summary>
        /// Returns true if SubmitToolOutputsRunRequest instances are equal
        /// </summary>
        /// <param name="other">Instance of SubmitToolOutputsRunRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SubmitToolOutputsRunRequest other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    ToolOutputs == other.ToolOutputs ||
                    ToolOutputs != null &&
                    ToolOutputs.SequenceEqual(other.ToolOutputs)
                ) && 
                (
                    Stream == other.Stream ||
                    Stream != null &&
                    Stream.Equals(other.Stream)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (ToolOutputs != null)
                    hashCode = hashCode * 59 + ToolOutputs.GetHashCode();
                    if (Stream != null)
                    hashCode = hashCode * 59 + Stream.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(SubmitToolOutputsRunRequest left, SubmitToolOutputsRunRequest right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(SubmitToolOutputsRunRequest left, SubmitToolOutputsRunRequest right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
